### ISSUE TITLE
cp is not part of windows in build.bat

### ISSUE THREAD

**Issue by aameen951** [Chronister/twc#7]
`'cp' is not recognized as an internal or external command, operable program or batch file.`

you might have some linux tools in your path. you can use `copy` instead.

**Comment by aameen951** [comment]
copy doesn't support copy multiple files to one directory in one command
and.... copy seems to not like forward slashes.... oh..   windows...

**Comment by chr-1x** [comment]
I'll deal with this tomorrow. If I recall I've used `xcopy` for this in the past, this one must have slipped through because I was making some last minute changes to the build process.

**Comment by chr-1x** [comment]
Turns out xcopy does not take multiple files, only thing that does on windows is Robocopy, and that produces a ton of extra output. I've updated the batch file to just use a bunch of individual xcopys.
